-- Business Profiles Sample Data
-- Insert sample business profiles into the business_profiles table

-- Note: Replace the instagramAccountId values with actual Instagram account IDs from your database
-- You can find existing Instagram account IDs by running: SELECT id, username FROM instagram_accounts;

INSERT INTO business_profiles (
    id,
    "brandName",
    "brandDescription", 
    industry,
    "targetAudience",
    "brandValues",
    "brandColors",
    "logoUrl",
    "visualStyle",
    "communicationTone",
    "contentThemes",
    "productCategories",
    "postingSchedule",
    "contentGuidelines",
    "prohibitedTopics",
    "instagramAccountId",
    "createdAt",
    "updatedAt"
) VALUES 
(
    gen_random_uuid(),
    'TechFlow Solutions',
    'Innovative software solutions for modern businesses. We specialize in cloud computing, AI integration, and digital transformation.',
    'Technology & Software',
    'Small to medium businesses, tech entrepreneurs, startup founders aged 28-45',
    'Innovation, Reliability, Customer Success, Transparency',
    '["#2563EB", "#1D4ED8", "#3B82F6", "#FFFFFF", "#F8FAFC"]'::jsonb,
    'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=200&h=200',
    'modern',
    'professional',
    'tech trends,business automation,productivity tips,case studies,industry insights',
    'software,consulting,cloud services,ai solutions',
    '{"monday": ["09:00", "15:00"], "tuesday": ["09:00", "15:00"], "wednesday": ["09:00", "15:00"], "thursday": ["09:00", "15:00"], "friday": ["09:00", "14:00"], "frequency": "daily"}'::jsonb,
    'Always maintain professional tone, use our brand colors in visuals, focus on value-driven content, include clear call-to-actions',
    'politics,religion,controversial social issues',
    'REPLACE_WITH_ACTUAL_INSTAGRAM_ACCOUNT_ID_1', -- Replace this with actual Instagram account ID
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Bloom & Bake Café',
    'Artisanal coffee and freshly baked goods made with love. A cozy neighborhood café where community meets quality.',
    'Food & Beverage',
    'Coffee enthusiasts, local community members, remote workers, food lovers aged 22-50',
    'Quality, Community, Sustainability, Authenticity',
    '["#8B5A3C", "#D2B48C", "#F5E6D3", "#2D5F3F", "#FFFFFF"]'::jsonb,
    'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=200&h=200',
    'cozy',
    'friendly',
    'coffee culture,baking tips,local events,seasonal specials,behind the scenes',
    'coffee,pastries,breakfast,lunch,catering',
    '{"monday": ["07:00", "16:00"], "tuesday": ["07:00", "16:00"], "wednesday": ["07:00", "16:00"], "thursday": ["07:00", "16:00"], "friday": ["07:00", "16:00"], "saturday": ["08:00", "15:00"], "sunday": ["08:00", "14:00"], "frequency": "twice_daily"}'::jsonb,
    'Use warm, inviting imagery, showcase fresh products, engage with local community, share stories behind recipes',
    'diet culture,health claims,negative competitor mentions',
    'REPLACE_WITH_ACTUAL_INSTAGRAM_ACCOUNT_ID_2',
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'FitLife Studio',
    'Premium fitness studio offering personalized training, group classes, and wellness coaching. Transform your body and mind.',
    'Health & Fitness',
    'Fitness enthusiasts, busy professionals, health-conscious individuals aged 25-55',
    'Health, Motivation, Community, Excellence',
    '["#FF6B35", "#F7931E", "#FFE066", "#2C3E50", "#FFFFFF"]'::jsonb,
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200',
    'energetic',
    'motivational',
    'workout routines,nutrition tips,success stories,fitness challenges,wellness advice',
    'personal training,group classes,nutrition coaching,fitness programs',
    '{"monday": ["06:00", "18:00"], "tuesday": ["06:00", "18:00"], "wednesday": ["06:00", "18:00"], "thursday": ["06:00", "18:00"], "friday": ["06:00", "17:00"], "saturday": ["08:00", "15:00"], "frequency": "daily"}'::jsonb,
    'Show diverse body types, focus on health over appearance, use action shots, include proper form demonstrations',
    'extreme diets,body shaming,unrealistic expectations',
    'REPLACE_WITH_ACTUAL_INSTAGRAM_ACCOUNT_ID_3',
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Verde Gardens',
    'Sustainable landscaping and garden design services. Creating beautiful outdoor spaces that work in harmony with nature.',
    'Landscaping & Gardening',
    'Homeowners, property managers, eco-conscious consumers aged 30-65',
    'Sustainability, Beauty, Craftsmanship, Environmental Stewardship',
    '["#4A7C59", "#8FBC8F", "#F0F8E8", "#8B4513", "#FFFFFF"]'::jsonb,
    'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=200&h=200',
    'natural',
    'educational',
    'garden design,plant care,sustainable practices,seasonal gardening,before/after transformations',
    'landscape design,garden maintenance,plant installation,hardscaping',
    '{"tuesday": ["10:00", "16:00"], "thursday": ["10:00", "16:00"], "saturday": ["09:00", "14:00"], "frequency": "three_times_weekly"}'::jsonb,
    'Showcase natural beauty, provide educational value, highlight eco-friendly practices, use high-quality plant photography',
    'chemical pesticides promotion,non-native invasive species',
    'REPLACE_WITH_ACTUAL_INSTAGRAM_ACCOUNT_ID_4',
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Artisan Jewelry Co.',
    'Handcrafted jewelry pieces that tell your unique story. Each piece is carefully designed and made with premium materials.',
    'Fashion & Accessories',
    'Fashion-forward women, gift buyers, jewelry enthusiasts aged 25-50',
    'Craftsmanship, Uniqueness, Quality, Personal Expression',
    '["#D4AF37", "#2C2C54", "#F8F8FF", "#C0C0C0", "#000000"]'::jsonb,
    'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=200&h=200',
    'elegant',
    'sophisticated',
    'jewelry styling,craftsmanship stories,new collections,styling tips,custom designs',
    'necklaces,earrings,bracelets,rings,custom jewelry',
    '{"monday": ["11:00", "19:00"], "wednesday": ["11:00", "19:00"], "friday": ["11:00", "19:00"], "sunday": ["14:00"], "frequency": "four_times_weekly"}'::jsonb,
    'Use elegant lighting for product shots, show jewelry being worn, highlight craftsmanship details, maintain luxury aesthetic',
    'fast fashion,mass production',
    'REPLACE_WITH_ACTUAL_INSTAGRAM_ACCOUNT_ID_5',
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Digital Nomad Hub',
    'Co-working space and community for digital nomads and remote workers. Work, connect, and explore in a vibrant environment.',
    'Co-working & Community',
    'Digital nomads, remote workers, freelancers, entrepreneurs aged 24-40',
    'Freedom, Community, Productivity, Adventure',
    '["#FF4081", "#00BCD4", "#FFC107", "#4CAF50", "#FFFFFF"]'::jsonb,
    'https://images.unsplash.com/photo-1497366216548-37526070297c?w=200&h=200',
    'vibrant',
    'casual',
    'remote work tips,community events,member spotlights,workspace features,location highlights',
    'co-working space,event hosting,community membership,networking',
    '{"monday": ["09:00", "17:00"], "tuesday": ["09:00", "17:00"], "wednesday": ["09:00", "17:00"], "thursday": ["09:00", "17:00"], "friday": ["09:00", "15:00"], "frequency": "daily"}'::jsonb,
    'Show diverse community members, highlight collaborative atmosphere, showcase amenities, promote events actively',
    'work-life balance myths,location discrimination',
    'REPLACE_WITH_ACTUAL_INSTAGRAM_ACCOUNT_ID_6',
    NOW(),
    NOW()
);

-- Optional: Query to verify the inserted data
-- SELECT id, "brandName", industry, "visualStyle", "communicationTone" FROM business_profiles ORDER BY "createdAt" DESC LIMIT 10;